# Generated by Django 3.0.7 on 2020-09-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0034_auto_20200919_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='стоимость'),
        ),
    ]
