# Generated by Django 3.0.7 on 2020-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20200920_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('UP', 'Необработанный'), ('PR', 'Обработанный')], default='Необработанный', max_length=20, verbose_name='Статус'),
        ),
    ]
