# Generated by Django 3.0.7 on 2020-09-20 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20200920_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_order_call',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 20, 12, 10, 29, 984478, tzinfo=utc), verbose_name='Связались с клиентом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time_order_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Заказ поступил'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_order_delivery',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Заказ отправлен'),
            preserve_default=False,
        ),
    ]
