# Generated by Django 3.0.7 on 2020-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20200920_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_order_call',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Связались с клиентом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заказ отправлен'),
        ),
    ]
