# Generated by Django 3.0.7 on 2020-09-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20200920_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CA', 'Наличные'), ('CC', 'Электронно')], default='Электронно', max_length=2, verbose_name='Тип оплаты'),
        ),
    ]
