# Generated by Django 3.0.7 on 2020-09-23 13:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('UP', 'Необработанный'), ('PR', 'Обработанный')], default='Необработанный', max_length=3, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CA', 'Наличные'), ('CC', 'Электронно')], default='Электронно', max_length=2, verbose_name='тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order_call',
            field=models.DateTimeField(blank=True, null=True, verbose_name='связались с клиентом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order_create',
            field=models.DateTimeField(auto_now=True, verbose_name='заказ поступил'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='заказ отправлен'),
        ),
    ]
