# Generated by Django 3.0.7 on 2020-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20200923_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='assets/', verbose_name='баннер')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
