# Generated by Django 3.0.7 on 2020-10-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'баннер', 'verbose_name_plural': 'баннеры'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='slug',
        ),
    ]
