# Generated by Django 3.0.7 on 2020-10-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_banner_banner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['banner_name'], 'verbose_name': 'баннер', 'verbose_name_plural': 'баннеры'},
        ),
    ]
