# Generated by Django 3.0.7 on 2020-10-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20201018_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['banner'], 'verbose_name': 'баннер', 'verbose_name_plural': 'баннеры'},
        ),
    ]
