# Generated by Django 3.0.7 on 2020-10-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20201018_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['image'], 'verbose_name': 'баннер', 'verbose_name_plural': 'баннеры'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='banner',
            new_name='image',
        ),
    ]
