# Generated by Django 3.0.7 on 2020-10-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20201018_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
