# Generated by Django 3.0.7 on 2020-10-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_banner_banner_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['banner_order'], 'verbose_name': 'баннер', 'verbose_name_plural': 'баннеры'},
        ),
    ]
