# Generated by Django 3.0.7 on 2020-10-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20201019_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners', verbose_name='баннер'),
        ),
    ]
