# Generated by Django 3.0.7 on 2020-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20201019_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(default='default', verbose_name='описание'),
            preserve_default=False,
        ),
    ]
