# Generated by Django 3.0.7 on 2021-01-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='баннер'),
        ),
    ]
