# Generated by Django 3.0.7 on 2021-01-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20210125_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='src',
        ),
    ]
