# Generated by Django 3.0.7 on 2021-01-25 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20210125_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_order',
            field=models.PositiveIntegerField(default=0, verbose_name='место баннера'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodcartapp.Order', verbose_name='заказ'),
        ),
    ]
