# Generated by Django 3.0.7 on 2021-01-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20210125_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='место баннера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('UP', 'Необработанный'), ('PR', 'Обработанный')], db_index=True, default='Необработанный', max_length=3, verbose_name='статус'),
        ),
    ]
