# Generated by Django 3.0.7 on 2021-01-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_auto_20210125_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time_order_call',
            new_name='call_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time_order_create',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time_order_delivery',
            new_name='delivery_time',
        ),
    ]
