# Generated by Django 3.0.7 on 2021-01-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0066_auto_20210126_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='payment',
            new_name='cost',
        ),
    ]
