# Generated by Django 3.0.7 on 2021-01-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0067_auto_20210126_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingridients',
            new_name='ingredients',
        ),
    ]
