# Generated by Django 3.0.7 on 2021-01-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0069_orderproduct_product_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='cost',
        ),
    ]
