# Generated by Django 3.0.7 on 2021-02-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0071_auto_20210128_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_address', models.CharField(max_length=200, verbose_name='адрес ресторана')),
                ('restaurant_lon', models.FloatField(verbose_name='долгота ресторана')),
                ('restaurant_lat', models.FloatField(verbose_name='широта ресторана')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='адрес доставки')),
                ('delivery_lon', models.FloatField(verbose_name='долгота доставки')),
                ('delivery_lat', models.FloatField(verbose_name='широта доставки')),
            ],
        ),
    ]
