# Generated by Django 3.0.7 on 2021-02-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0073_auto_20210204_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery_location',
            new_name='DeliveryLocation',
        ),
        migrations.RenameModel(
            old_name='Restaurant_location',
            new_name='RestaurantLocation',
        ),
    ]
