# Generated by Django 3.2.8 on 2022-01-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0075_auto_20220103_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_address', models.CharField(max_length=200, verbose_name='адрес ресторана')),
                ('restaurant_lon', models.FloatField(verbose_name='долгота ресторана')),
                ('restaurant_lat', models.FloatField(verbose_name='широта ресторана')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='адрес доставки')),
                ('delivery_lon', models.FloatField(verbose_name='долгота доставки')),
                ('delivery_lat', models.FloatField(verbose_name='широта доставки')),
            ],
        ),
    ]
