# Generated by Django 3.2.8 on 2022-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0077_auto_20220109_1443'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['restaurant_address', 'delivery_address'], name='foodcartapp_restaur_ed2898_idx'),
        ),
    ]
