# Generated by Django 3.2.8 on 2022-01-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0079_auto_20220109_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта доставки'),
        ),
        migrations.AlterField(
            model_name='location',
            name='delivery_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота доставки'),
        ),
        migrations.AlterField(
            model_name='location',
            name='restaurant_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта ресторана'),
        ),
        migrations.AlterField(
            model_name='location',
            name='restaurant_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота ресторана'),
        ),
    ]
