# Generated by Django 3.2.8 on 2022-01-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0080_auto_20220110_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='delivery_address',
            field=models.CharField(max_length=200, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='location',
            name='restaurant_address',
            field=models.CharField(max_length=200, verbose_name='адрес ресторана'),
        ),
    ]
