# Generated by Django 3.2.8 on 2022-01-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0081_auto_20220113_0511'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('restaurant_address', 'delivery_address'), name='unique_couple_addresses'),
        ),
    ]
