# Generated by Django 3.2.8 on 2022-01-15 03:44

from django.db import migrations, models
import enumfields.fields
import foodcartapp.enums


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0083_auto_20220115_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=enumfields.fields.EnumField(default='необработанный', enum=foodcartapp.enums.OrderStatus, max_length=20, verbose_name='статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=enumfields.fields.EnumField(default='cash', enum=foodcartapp.enums.PaymentMethod, max_length=20, verbose_name='метод оплаты'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='foodcartapp_order_s_91868e_idx'),
        ),
    ]
