# Generated by Django 3.2.8 on 2022-01-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0084_auto_20220115_0344'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_order_s_91868e_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', 'create_time', 'call_time', 'delivery_time'], name='foodcartapp_order_s_70329f_idx'),
        ),
    ]
