# Generated by Django 3.2.8 on 2022-01-15 03:49

from django.db import migrations
import enumfields.fields
import foodcartapp.enums


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0085_auto_20220115_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=enumfields.fields.EnumField(default='необработанный', enum=foodcartapp.enums.OrderStatus, max_length=20, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=enumfields.fields.EnumField(enum=foodcartapp.enums.PaymentMethod, max_length=20, verbose_name='метод оплаты'),
        ),
    ]
