# Generated by Django 3.2.8 on 2022-01-15 04:34

from django.db import migrations
import enumfields.fields
import foodcartapp.enums


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0087_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=enumfields.fields.EnumField(default='банковской картой', enum=foodcartapp.enums.PaymentMethod, max_length=20, verbose_name='метод оплаты'),
        ),
    ]
