# Generated by Django 3.2.8 on 2022-04-16 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0088_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default='1.0', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость 1ед'),
            preserve_default=False,
        ),
    ]
