# Generated by Django 3.2.8 on 2022-05-27 03:38

from django.db import migrations
import enumfields.fields
import foodcartapp.enums


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0092_auto_20220527_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=enumfields.fields.EnumField(enum=foodcartapp.enums.PaymentMethod, max_length=20, verbose_name='метод оплаты'),
        ),
    ]
