# Generated by Django 3.2.8 on 2022-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0094_auto_20220601_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
            ],
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['address'], name='foodcartapp_address_628f12_idx'),
        ),
    ]
