# Generated by Django 3.2.8 on 2022-06-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0095_auto_20220606_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.deliverylocation'),
        ),
    ]
