# Generated by Django 3.2.8 on 2022-06-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0096_order_delivery_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
