# Generated by Django 3.2.8 on 2022-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0097_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
