# Generated by Django 3.2.8 on 2022-06-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0098_alter_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
            preserve_default=False,
        ),
    ]
